# =========================================================================
#   Ceedling - Test-Centered Build System for C
# =========================================================================

---
:project:
  :which_ceedling: gem
  :ceedling_version: 1.0.1

  :use_mocks: TRUE
  :use_test_preprocessor: :none
  :use_deep_preprocessor: :none
  :use_backtrace: :simple
  :use_decorators: :auto

  :build_root: build
  :test_file_prefix: test_
  :default_tasks:
    - test:all

  :test_threads: 8
  :compile_threads: 8

  :release_build: FALSE

:mixins:
  :enabled: []
  :load_paths: []

:test_build:
  :use_assembly: FALSE

:release_build:
  :output: MyApp.out
  :use_assembly: FALSE
  :artifacts: []

:plugins:
  :enabled:
    - module_generator
    - gcov
    - report_tests_pretty_stdout

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - src/**
  :support:
    - test/support
  :libraries: []

:files:
  :test: []
  :source: []

:defines:
  :test:
    - TEST
  :release: []

:cmock:
  :plugins:
    - :ignore
    - :callback
  :verbosity: 2
  :when_no_prototypes: :warn
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8
  :memcmp_if_unknown: true
  :when_ptr: :compare_data

:unity:
  :defines:
    - UNITY_EXCLUDE_FLOAT

:environment: []

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:gcov:
  :summaries: TRUE
  :report_task: FALSE
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :html: true
    :html_details: true
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :output: build/artifacts/gcov/GcovCoverageResults.html

:tools:
  :gcov_compiler:
    :executable: gcc
    :name: 'GCC GCOV Compiler'
    :arguments:
      - -fprofile-arcs
      - -ftest-coverage
      - -g
      - -O0
  :gcov_linker:
    :executable: gcc
    :name: 'GCC GCOV Linker'
    :arguments:
      - -fprofile-arcs
      - -ftest-coverage
      - -g
      - -O0
...